sudo: required
services:
  - docker

before_install:
  - docker build -t biswajit713/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run biswajit713/react-test npm run test -- --coverage

after_success:
  - docker build -t biswajit713/multi-client ./client
  - docker build -t biswajit713/multi-nginx  ./nginx
  - docker build -t biswajit713/multi-server ./server
  - docker build -t biswajit713/multi-worker ./worker  

  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push biswajit713/multi-client
  - docker push biswajit713/multi-nginx
  - docker push biswajit713/multi-server
  - docker push biswajit713/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-560473013098
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY